version: 0.0
os: linux
files:
  - source: /wise.war
    destination: /home/ubuntu/build
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
  AfterInstall:
    - location: afterInstall.sh
  ApplicationStart:
    - location: applicationStart.sh
